package org.medcep.integracao.taiga;

public enum MedidasTaiga
{
    PONTOS_ALOCADOS, PONTOS_FECHADOS_POR_PAPEL, VELOCIDADE,
    PONTOS_DEFINIDOS, PONTOS_FECHADOS, PONTOS_DEFINIDOS_POR_PAPEL,
    TOTAL_MARCOS, PONTOS_ALOCADOS_POR_PAPEL, TOTAL_PONTOS
};